//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Stalker_net.rc
//
#define IDD_STALKER_NET_DIALOG          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_SUBDLG                      105
#define IDR_MAINFRAME                   128
#define IDD_SERVERDLG                   129
#define IDR_MAINFRAME1                  129
#define IDD_CLIENTDLG                   130
#define IDD_GAMETYPE                    131
#define IDD_GAMEOPTIONS                 132
#define IDD_RESPAWN                     136
#define IDD_SERVEROPTS2                 137
#define IDD_SERVEROPT                   138
#define IDB_BITMAP1                     145
#define IDB_BITMAP2                     146
#define IDB_PBGS261                     150
#define IDB_PBGS130                     156
#define IDD_CDKEYDLG                    157
#define IDD_PSWDLG                      158
#define IDD_WEATHEROPTIONS              159
#define IDD_SPECTATOROPTS               160
#define IDD_PORTSDLG                    161
#define IDC_TAB1                        1000
#define IDC_CATCHINPUT                  1001
#define IDC_CATCHINPUT2                 1002
#define IDC_BUILD                       1002
#define IDC_NOPREFETCH                  1003
#define IDC_MAPLIST                     1004
#define IDC_BUILD2                      1004
#define IDC_R2                          1004
#define IDC_MAPLIST2                    1005
#define IDC_R3                          1005
#define IDC_DISTORT                     1005
#define IDC_STARTSERVER                 1009
#define IDC_JOIN                        1011
#define IDC_REFRESH                     1012
#define IDC_GSUPDATELIST                1013
#define IDC_GSREFRESHLIST               1014
#define IDC_SERVERSLIST                 1016
#define IDC_PLAYERNAME                  1021
#define IDC_TIMELIMIT                   1024
#define IDC_GAMEDM                      1025
#define IDC_GAMETDM                     1026
#define IDC_GAMEAHUNT                   1027
#define IDC_SLIDER1                     1028
#define IDC_FFAMOUNT                    1029
#define IDC_ARTEFACTSNUM                1030
#define IDC_FL                          1031
#define IDC_TL                          1032
#define IDC_FF                          1033
#define IDC_AN                          1034
#define IDC_DEDICATED                   1035
#define IDC_ARD                         1035
#define IDC_FRAGLIMIT                   1036
#define IDC_SPECTATORONLY               1036
#define IDC_ARTEFACTDELAY               1037
#define IDC_PUBLIC                      1037
#define IDC_ARTEFACTSTAY                1038
#define IDC_REINFORCEMENT               1038
#define IDC_CDKEY                       1038
#define IDC_AST                         1039
#define IDC_ARTEFACTCAPTURED            1039
#define IDC_REINFORCEMENTTIME           1040
#define IDC_NOANOMALIES                 1040
#define IDC_AUTOTEAMBALANCE             1041
#define IDC_PROINTFREEZETIME            1041
#define IDC_SPECTRTIME                  1042
#define IDC_FRIENDLYINDICATORS          1042
#define IDC_DAMAGEBLOCKLIMIT            1042
#define IDC_SP_FEM                      1042
#define IDC_DMGBLKIND                   1043
#define IDC_ANMSETLENGTH                1043
#define IDC_SP_LAM                      1043
#define IDC_FORCERESPAWN                1044
#define IDC_AST2                        1044
#define IDC_SP_FLM                      1044
#define IDC_FORCERESPAWNTIME            1045
#define IDC_ANMSETLENGTH2               1045
#define IDC_WARMUPTIME                  1045
#define IDC_SP_TEAMONLY                 1045
#define IDC_HOSTNAME                    1046
#define IDC_WARMUPSTATIC                1046
#define IDC_PASSWORD                    1047
#define IDC_INTERNET                    1047
#define IDC_AUTOTEAMSWAP                1047
#define IDC_MAXPLAYERS                  1048
#define IDC_LAN                         1048
#define IDC_FRIENDLYINDICATORS2         1048
#define IDC_FRIENDLYNAMES               1048
#define IDC_SERVERPORT                  1049
#define IDC_GAMESPYPORT                 1050
#define IDC_CLIENTPORT                  1051
#define IDC_FEMPTY                      1061
#define IDC_FFULL                       1062
#define IDC_CDK1                        1062
#define IDC_FPASSWORD                   1063
#define IDC_CDKEYBTN                    1063
#define IDC_FNOPASSWORD                 1064
#define IDC_EDIT1                       1064
#define IDC_LOGSPATH                    1064
#define IDC_FLISTEN                     1065
#define IDC_FNOPUNKBUSTER               1066
#define IDC_CDK2                        1066
#define IDC_FNOFF                       1067
#define IDC_CDK3                        1067
#define IDC_SERVEROPTIONS               1067
#define IDC_CDK4                        1068
#define IDC_2LIST2                      1068
#define IDC_2LIST                       1069
#define IDC_MAPROTATION                 1071
#define IDC_MAPROTFILE                  1072
#define IDC_VOTINGALLOWED               1073
#define IDC_STARTWEATHER                1075
#define IDC_WEATHERSPEED                1076
#define IDC_SP_FFM                      1077
#define IDC_PORTS                       1079
#define IDC_SV_PORTBUTTON               1080
#define IDC_CLPORTBUTTON                1081
#define IDC_CL_PORTBUTTON               1081
#define IDC_GS_PORTBUTTON               1082

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
