#ifndef CONFIGURATOR_DEFINES_H
#define CONFIGURATOR_DEFINES_H
#define SS_DUST
#define USE_VOLUMETRIC_DUST
#define USE_MOON_ROAD
#define FL_USE_LONG_FLARE
//#define SSDO_USE_INDIRECT_BOUNCES
//#define DDOF_CHROMATIC_ABERRATION

#define SS_VOL_MAX_INTENSITY float(0.170)
#define VOL_LIGHT_MAX_INTENSITY float(0.015)
#define SSDO_BLEND_FACTOR float(0.750)
#define HBAO_BLEND_FACTOR float(0.700)
#define ZDOF_INTENSITY float(0.600)
#define RDOF_INTENSITY float(0.050)
#define PUDDLES_GROW_SPEED float(0.200)
#endif
