//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurator.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr_FR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr_FR() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configurator.Resources.fr-FR", typeof(fr_FR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tremblement de la caméra et flash.
        /// </summary>
        internal static string actor_hit_all {
            get {
                return ResourceManager.GetString("actor_hit_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на tremblement de la caméra.
        /// </summary>
        internal static string actor_hit_camera {
            get {
                return ResourceManager.GetString("actor_hit_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на débranché.
        /// </summary>
        internal static string actor_hit_disabled {
            get {
                return ResourceManager.GetString("actor_hit_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option permet à la musique d&apos;ambiance dans le jeu. La musique varie d&apos;un endroit à l&apos;autre.
        /// </summary>
        internal static string ambient_music_desc {
            get {
                return ResourceManager.GetString("ambient_music_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Musique ambiante.
        /// </summary>
        internal static string ambient_music_name {
            get {
                return ResourceManager.GetString("ambient_music_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lorsqu&apos;elle est activée cette option désactivée à l&apos;aide de munitions pour fusils de ruck. La place emballe avec des balles sur la bande à la place.
        /// </summary>
        internal static string ammo_on_belt_desc {
            get {
                return ResourceManager.GetString("ammo_on_belt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Munitions à la ceinture.
        /// </summary>
        internal static string ammo_on_belt_name {
            get {
                return ResourceManager.GetString("ammo_on_belt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на fichier introuvable.
        /// </summary>
        internal static string CANT_FIND_FILE {
            get {
                return ResourceManager.GetString("CANT_FIND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compte-à-rebours de la centrale, min.
        /// </summary>
        internal static string chaes_timer_name {
            get {
                return ResourceManager.GetString("chaes_timer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active l&apos;effet d&apos;aberration chromatique (dispertion de la lumière sur la lentille).
        /// </summary>
        internal static string chrom_aberr_desc {
            get {
                return ResourceManager.GetString("chrom_aberr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effet &quot;aberration chromatique&quot;.
        /// </summary>
        internal static string chrom_aberr_name {
            get {
                return ResourceManager.GetString("chrom_aberr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gain de luminosité des pixels floutés quand le DDOF est activé. Une valeur élevée donne un joli flou des sources de lumière, mais peut rendre le ciel trop brillant selon la météo. Modifiable de 1 à 4..
        /// </summary>
        internal static string ddof_gain_desc {
            get {
                return ResourceManager.GetString("ddof_gain_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Luminosité du DDOF.
        /// </summary>
        internal static string ddof_gain_name {
            get {
                return ResourceManager.GetString("ddof_gain_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option gère les textures dynamiques à l&apos;écran - le masque à gaz ou le casque de la combinaison est visible, ainsi que la condensation dynamique, le sang et les égratinures..
        /// </summary>
        internal static string dinamicheski_hud_desc {
            get {
                return ResourceManager.GetString("dinamicheski_hud_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hud dynamique.
        /// </summary>
        internal static string dinamicheski_hud_name {
            get {
                return ResourceManager.GetString("dinamicheski_hud_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DOF (Profondeur du champ de vue).
        /// </summary>
        internal static string dof {
            get {
                return ResourceManager.GetString("dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option gère l&apos;apparition périodique de stalkers et de monstres en des lieux aléatoires. Cela peut changer complètement le jeu et rendre certaines situations imprévisibles..
        /// </summary>
        internal static string dop_spawn_desc {
            get {
                return ResourceManager.GetString("dop_spawn_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activer add. spawn après les émissions.
        /// </summary>
        internal static string dop_spawn_name {
            get {
                return ResourceManager.GetString("dop_spawn_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Messages dynamiques.
        /// </summary>
        internal static string dynamic_news {
            get {
                return ResourceManager.GetString("dynamic_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active des nouvelles dynamiques sur la mort des stalkers dans le jeu..
        /// </summary>
        internal static string dynamic_news_desc {
            get {
                return ResourceManager.GetString("dynamic_news_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Anglais.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probabilité de trouver un exosquelette sur le cadavre d&apos;un stalker. La valeur peut être modifiée de 1 à 15..
        /// </summary>
        internal static string exo_prob_desc {
            get {
                return ResourceManager.GetString("exo_prob_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probabilité de trouver un exosquelette.
        /// </summary>
        internal static string exo_prob_name {
            get {
                return ResourceManager.GetString("exo_prob_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rayon min. et max. [5,140].
        /// </summary>
        internal static string fov_volume_desc {
            get {
                return ResourceManager.GetString("fov_volume_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FOV (champ de vue).
        /// </summary>
        internal static string fov_volume_name {
            get {
                return ResourceManager.GetString("fov_volume_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité de l&apos;Ambient Occlusion (HBAO). Modifiable de 0 à 100..
        /// </summary>
        internal static string hbao_int_desc {
            get {
                return ResourceManager.GetString("hbao_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité du HBAO.
        /// </summary>
        internal static string hbao_int_name {
            get {
                return ResourceManager.GetString("hbao_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Une imitation de lumière dynamique pour le SSDO. Réduit les FPS mais les ombres de l&apos;Ambiant Occlusion ont un meilleur rendu..
        /// </summary>
        internal static string indirect_bounce_desc {
            get {
                return ResourceManager.GetString("indirect_bounce_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rayons indirects pour le SSDO.
        /// </summary>
        internal static string indirect_bounce_name {
            get {
                return ResourceManager.GetString("indirect_bounce_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active des rayons lumineux horizontaux émananant des lampes..
        /// </summary>
        internal static string long_flare_desc {
            get {
                return ResourceManager.GetString("long_flare_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Halo des lampes.
        /// </summary>
        internal static string long_flare_name {
            get {
                return ResourceManager.GetString("long_flare_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active la récupération lente de la santé pour rendre le jeu plus réaliste..
        /// </summary>
        internal static string medlen_lek_desc {
            get {
                return ResourceManager.GetString("medlen_lek_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Soins lents des médikits.
        /// </summary>
        internal static string medlen_lek_name {
            get {
                return ResourceManager.GetString("medlen_lek_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquence du respawn.
        /// </summary>
        internal static string mnog_resp_name {
            get {
                return ResourceManager.GetString("mnog_resp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active les reflets du soleil ou de la lune sur l&apos;eau..
        /// </summary>
        internal static string moonroad_desc {
            get {
                return ResourceManager.GetString("moonroad_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reflets sur l&apos;eau.
        /// </summary>
        internal static string moonroad_name {
            get {
                return ResourceManager.GetString("moonroad_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquences des nouvelles dynamiques - plus la valeur est basse plus il y a de messages..
        /// </summary>
        internal static string news_freq_desc {
            get {
                return ResourceManager.GetString("news_freq_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquence des messages.
        /// </summary>
        internal static string news_freq_name {
            get {
                return ResourceManager.GetString("news_freq_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Impossible de se connecter au serveur. Vérifiez votre connection internet..
        /// </summary>
        internal static string no_internet {
            get {
                return ResourceManager.GetString("no_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vous ne pouvez pas trouver le fichier de localisation OGSE.
        /// </summary>
        internal static string NO_LOCALE {
            get {
                return ResourceManager.GetString("NO_LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pas de mise-à-jour.
        /// </summary>
        internal static string no_update {
            get {
                return ResourceManager.GetString("no_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNJ.
        /// </summary>
        internal static string NPC {
            get {
                return ResourceManager.GetString("NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Off.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option gère le comportement des PNJ dans le jeu. Ils se battent entre eux et avec les mutants, ils ramassent les objets et les armes. Ces actions sont décrites dans les messages..
        /// </summary>
        internal static string offline_alife_desc {
            get {
                return ResourceManager.GetString("offline_alife_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Offline alife.
        /// </summary>
        internal static string offline_alife_name {
            get {
                return ResourceManager.GetString("offline_alife_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Le patch est téléchargé!.
        /// </summary>
        internal static string patch_downloaded {
            get {
                return ResourceManager.GetString("patch_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquence de réapparition des nouveaux mutants (en heures du jeu). Peut modifier légèrement l&apos;expérience selon la valeur choisie (une ou deux heures).
        /// </summary>
        internal static string period_resp_new_desc {
            get {
                return ResourceManager.GetString("period_resp_new_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquence de réapparition des mutants.
        /// </summary>
        internal static string period_resp_new_name {
            get {
                return ResourceManager.GetString("period_resp_new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquence de réapparition des PNJ secondaires et des mutants (en heures du jeu). À 0 leur réapparition se produit immédiatement quand un endroit vide est disponible..
        /// </summary>
        internal static string period_resp_old_desc {
            get {
                return ResourceManager.GetString("period_resp_old_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquence de réapparition des PNJ ordinaires.
        /// </summary>
        internal static string period_resp_old_name {
            get {
                return ResourceManager.GetString("period_resp_old_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Joueur.
        /// </summary>
        internal static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option permet de basculer des effets de caméra en fonction de l&apos;état de santé de l&apos;acteur..
        /// </summary>
        internal static string plohoe_samochustv_desc {
            get {
                return ResourceManager.GetString("plohoe_samochustv_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effets sur la santé.
        /// </summary>
        internal static string plohoe_samochustv_name {
            get {
                return ResourceManager.GetString("plohoe_samochustv_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activation automatique de la vision nocturne sur les lunettes de visée.
        /// </summary>
        internal static string pnv_autostart_desc {
            get {
                return ResourceManager.GetString("pnv_autostart_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vision nocturne des lunettes.
        /// </summary>
        internal static string pnv_autostart_name {
            get {
                return ResourceManager.GetString("pnv_autostart_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option désactive la vision nocturne lors du zoom avec une lunette ou des jumelles. Les jumelles et lunettes nocturnes ne sont pas affectées..
        /// </summary>
        internal static string pnv_disabling_desc {
            get {
                return ResourceManager.GetString("pnv_disabling_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vision nocturne désactivée lors du zoom.
        /// </summary>
        internal static string pnv_disabling_name {
            get {
                return ResourceManager.GetString("pnv_disabling_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option gère les effets secondaires en cas d&apos;overdose.
        /// </summary>
        internal static string poboch_lek_desc {
            get {
                return ResourceManager.GetString("poboch_lek_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effet secondaire des médicaments.
        /// </summary>
        internal static string poboch_lek_name {
            get {
                return ResourceManager.GetString("poboch_lek_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string popadanie_po_ger_desc {
            get {
                return ResourceManager.GetString("popadanie_po_ger_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effet des impacts de balles sur le personnage.
        /// </summary>
        internal static string popadanie_po_ger_name {
            get {
                return ResourceManager.GetString("popadanie_po_ger_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active les émissions-psi après les émissions ordinaires avec une probabilité dépendante du lieu où se trouve le personnage..
        /// </summary>
        internal static string psy_surges_desc {
            get {
                return ResourceManager.GetString("psy_surges_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Emission-psi.
        /// </summary>
        internal static string psy_surges_name {
            get {
                return ResourceManager.GetString("psy_surges_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option gère l&apos;apparition des zones-psi: elles peuvent être connectées aux émissions-psi, aux émissions ordinaires ou complètement désactivées..
        /// </summary>
        internal static string psyzones_desc {
            get {
                return ResourceManager.GetString("psyzones_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на désactivé.
        /// </summary>
        internal static string psyzones_disabled {
            get {
                return ResourceManager.GetString("psyzones_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zones-psi.
        /// </summary>
        internal static string psyzones_name {
            get {
                return ResourceManager.GetString("psyzones_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на connectées aux émissions-psi.
        /// </summary>
        internal static string psyzones_to_psyvybros {
            get {
                return ResourceManager.GetString("psyzones_to_psyvybros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на connectées aux émissions ordinaires.
        /// </summary>
        internal static string psyzones_to_vybros {
            get {
                return ResourceManager.GetString("psyzones_to_vybros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rapidité de la formation des mares quand il pleut. Modifiable de 0 à 100..
        /// </summary>
        internal static string puddles_grow_desc {
            get {
                return ResourceManager.GetString("puddles_grow_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Formation des mares.
        /// </summary>
        internal static string puddles_grow_name {
            get {
                return ResourceManager.GetString("puddles_grow_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option permet d&apos;avoir un contenu aléatoire des caches, à l&apos;exception de celles qui sont spécifiquement nommées..
        /// </summary>
        internal static string random_stashes_desc {
            get {
                return ResourceManager.GetString("random_stashes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contenu aléatoire des caches.
        /// </summary>
        internal static string random_stashes_name {
            get {
                return ResourceManager.GetString("random_stashes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effet de contre-champ lors de la recharge d&apos;une arme. Modifiable de 0 à 100..
        /// </summary>
        internal static string rdof_int_desc {
            get {
                return ResourceManager.GetString("rdof_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité du DOF pendant une recharge.
        /// </summary>
        internal static string rdof_int_name {
            get {
                return ResourceManager.GetString("rdof_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russe.
        /// </summary>
        internal static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lumière volumétrique.
        /// </summary>
        internal static string shafts {
            get {
                return ResourceManager.GetString("shafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option permet de voir le contenu d&apos;une cache en passant la souris dessus..
        /// </summary>
        internal static string show_stashes_desc {
            get {
                return ResourceManager.GetString("show_stashes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Montrer le contenu des caches.
        /// </summary>
        internal static string show_stashes_name {
            get {
                return ResourceManager.GetString("show_stashes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option permet aux PNJ de dormir. Quand il fait nuit ils sont fatigués et ils essayent de dormir s&apos;il n&apos;y a pas de danger aux alentours..
        /// </summary>
        internal static string son_desc {
            get {
                return ResourceManager.GetString("son_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activer le sommeil des PNJ.
        /// </summary>
        internal static string son_name {
            get {
                return ResourceManager.GetString("son_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active l&apos;effet poussière dans les rayons de soleil du type &quot;Crysis&quot;.
        /// </summary>
        internal static string ss_dust_desc {
            get {
                return ResourceManager.GetString("ss_dust_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poussière dans les rayons de soleil.
        /// </summary>
        internal static string ss_dust_name {
            get {
                return ResourceManager.GetString("ss_dust_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active l&apos;effet poussière dans la lumière des lampes.
        /// </summary>
        internal static string ss_volume_dust_desc {
            get {
                return ResourceManager.GetString("ss_volume_dust_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poussière dans la lumière des lampes.
        /// </summary>
        internal static string ss_volume_dust_name {
            get {
                return ResourceManager.GetString("ss_volume_dust_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité du Screen Space Dynamic Occlusion. Modifiable de 0 à 100.
        /// </summary>
        internal static string ssdo_int_desc {
            get {
                return ResourceManager.GetString("ssdo_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité du SSDO.
        /// </summary>
        internal static string ssdo_int_name {
            get {
                return ResourceManager.GetString("ssdo_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probabilité d&apos;apparition de caches au contenu aléatoire.
        /// </summary>
        internal static string stashes_desc {
            get {
                return ResourceManager.GetString("stashes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probabilité de trouver des caches, %.
        /// </summary>
        internal static string stashes_name {
            get {
                return ResourceManager.GetString("stashes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Caches.
        /// </summary>
        internal static string stashes_settings {
            get {
                return ResourceManager.GetString("stashes_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probabilité de trouver une combinaison ordinaire sur le cadavre d&apos;un stalker. La valeur peut être modifiée de 1 à 25. N&apos;affecte pas la probabilité de trouver un exosquelette..
        /// </summary>
        internal static string suit_prob_desc {
            get {
                return ResourceManager.GetString("suit_prob_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probabilité de trouver une combinaison.
        /// </summary>
        internal static string suit_prob_name {
            get {
                return ResourceManager.GetString("suit_prob_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Temps du jeu (en heures). Il est possible de lui donner un effet aléatoire (de -4 à 4h).
        /// </summary>
        internal static string surge_timer_desc {
            get {
                return ResourceManager.GetString("surge_timer_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fréquence des émissions.
        /// </summary>
        internal static string surge_timer_name {
            get {
                return ResourceManager.GetString("surge_timer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Plus la valeur est basse, plus les jours sont longs.
        /// </summary>
        internal static string time_factor_desc {
            get {
                return ResourceManager.GetString("time_factor_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Facteur temps.
        /// </summary>
        internal static string time_factor_name {
            get {
                return ResourceManager.GetString("time_factor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Heure du commencement du jeu.
        /// </summary>
        internal static string time_start_name {
            get {
                return ResourceManager.GetString("time_start_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mise-à-jour disponible.
        /// </summary>
        internal static string update_available {
            get {
                return ResourceManager.GetString("update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autre.
        /// </summary>
        internal static string various {
            get {
                return ResourceManager.GetString("various", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min. et max. [40,100] kg.
        /// </summary>
        internal static string ves_desc {
            get {
                return ResourceManager.GetString("ves_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Poids maximal en kg.
        /// </summary>
        internal static string ves_name {
            get {
                return ResourceManager.GetString("ves_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active l&apos;effet &quot;vignette&quot; à l&apos;écran (bords de l&apos;écran plus foncés que le centre).
        /// </summary>
        internal static string vignette_desc {
            get {
                return ResourceManager.GetString("vignette_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité de l&apos;effet &quot;vignette&quot;. Modifiable de 0 à 100. 100 - bordures complètement noires..
        /// </summary>
        internal static string vignette_int_desc {
            get {
                return ResourceManager.GetString("vignette_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité de l&apos;effet &quot;vignette&quot;.
        /// </summary>
        internal static string vignette_int_name {
            get {
                return ResourceManager.GetString("vignette_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vignette.
        /// </summary>
        internal static string vignette_name {
            get {
                return ResourceManager.GetString("vignette_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option contrôle l&apos;intensité des lumières volumétriques des lampes. Modifiable de 0 à 100..
        /// </summary>
        internal static string vol_light_max_int_desc {
            get {
                return ResourceManager.GetString("vol_light_max_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité de la lumière volumétrique des lampes.
        /// </summary>
        internal static string vol_light_max_int_name {
            get {
                return ResourceManager.GetString("vol_light_max_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option contrôle l&apos;intensité de la lumière volumétrique du soleil (de type &quot;Clear Sky&quot;). Modifiable de 0 à 100..
        /// </summary>
        internal static string vol_max_int_desc {
            get {
                return ResourceManager.GetString("vol_max_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité de la lumière volumétrique du soleil.
        /// </summary>
        internal static string vol_max_int_name {
            get {
                return ResourceManager.GetString("vol_max_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attendez la fin du téléchargement.
        /// </summary>
        internal static string wait_for_download {
            get {
                return ResourceManager.GetString("wait_for_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на clair.
        /// </summary>
        internal static string weather_bright {
            get {
                return ResourceManager.GetString("weather_bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на standard.
        /// </summary>
        internal static string weather_default {
            get {
                return ResourceManager.GetString("weather_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pluvieux.
        /// </summary>
        internal static string weather_rainy {
            get {
                return ResourceManager.GetString("weather_rainy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option change dans le jeu prédéfini météo.
        /// </summary>
        internal static string weather_type_desc {
            get {
                return ResourceManager.GetString("weather_type_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Météo.
        /// </summary>
        internal static string weather_type_name {
            get {
                return ResourceManager.GetString("weather_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zone.
        /// </summary>
        internal static string world_settings {
            get {
                return ResourceManager.GetString("world_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cette option active les giclures de sang sur le masque quand un PNJ est très près du joueur.
        /// </summary>
        internal static string zalyap_hud_desc {
            get {
                return ResourceManager.GetString("zalyap_hud_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sang sur le masque.
        /// </summary>
        internal static string zalyap_hud_name {
            get {
                return ResourceManager.GetString("zalyap_hud_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité du contre-champ lors d&apos;un zoom. Modifiable de 0 à 100..
        /// </summary>
        internal static string zdof_int_desc {
            get {
                return ResourceManager.GetString("zdof_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intensité du DOF lors du zoom.
        /// </summary>
        internal static string zdof_int_name {
            get {
                return ResourceManager.GetString("zdof_int_name", resourceCulture);
            }
        }
    }
}
