//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configurator.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configurator.Resources.ru-RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сотрясение камеры с засветкой.
        /// </summary>
        public static string actor_hit_all {
            get {
                return ResourceManager.GetString("actor_hit_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сотрясение камеры.
        /// </summary>
        public static string actor_hit_camera {
            get {
                return ResourceManager.GetString("actor_hit_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отключены.
        /// </summary>
        public static string actor_hit_disabled {
            get {
                return ResourceManager.GetString("actor_hit_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта настройка включает фоновую музыку, которая играет во время игры. Она различается в зависимости от локации..
        /// </summary>
        public static string ambient_music_desc {
            get {
                return ResourceManager.GetString("ambient_music_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фоновая музыка.
        /// </summary>
        public static string ambient_music_name {
            get {
                return ResourceManager.GetString("ambient_music_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта настройка отключает использование патронов для оружия из рюкзака. Используются только те патроны, которые игрок поместил на пояс..
        /// </summary>
        public static string ammo_on_belt_desc {
            get {
                return ResourceManager.GetString("ammo_on_belt_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Патроны на поясе.
        /// </summary>
        public static string ammo_on_belt_name {
            get {
                return ResourceManager.GetString("ammo_on_belt_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден файл.
        /// </summary>
        public static string CANT_FIND_FILE {
            get {
                return ResourceManager.GetString("CANT_FIND_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таймер выброса на ЧАЭС, мин.
        /// </summary>
        public static string chaes_timer_name {
            get {
                return ResourceManager.GetString("chaes_timer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция  включает эффект хроматической аберрации (разложение света на спектр из-за дефектов линзы).
        /// </summary>
        public static string chrom_aberr_desc {
            get {
                return ResourceManager.GetString("chrom_aberr_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эффект хроматической аберрации.
        /// </summary>
        public static string chrom_aberr_name {
            get {
                return ResourceManager.GetString("chrom_aberr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коэффициент усиления яркости заблюренных областей при включенном эффекте глубины поля зрения. Большие значения дают красивое размытие источников света, но могут приводить к излишне яркому небу при некоторой погоде. Регулируется от 1 до 4..
        /// </summary>
        public static string ddof_gain_desc {
            get {
                return ResourceManager.GetString("ddof_gain_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Усиление DDOF.
        /// </summary>
        public static string ddof_gain_name {
            get {
                return ResourceManager.GetString("ddof_gain_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает отображение противогаза или маски костюма, что включает также эффекты запотевания стёкол от дыхания и, в зависимости от состояния, трещины, пятна крови и царапины на стекле..
        /// </summary>
        public static string dinamicheski_hud_desc {
            get {
                return ResourceManager.GetString("dinamicheski_hud_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Динамический худ.
        /// </summary>
        public static string dinamicheski_hud_name {
            get {
                return ResourceManager.GetString("dinamicheski_hud_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Глубина поля зрения.
        /// </summary>
        public static string dof {
            get {
                return ResourceManager.GetString("dof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция определяет, будут ли в игре периодически спавниться дополнительные враги и монстры в произвольных местах. Опция серьёзно оживляет игру, однако увеличивает нагрузку на систему, и может сделать прохождение квестовых сценок непредсказуемым..
        /// </summary>
        public static string dop_spawn_desc {
            get {
                return ResourceManager.GetString("dop_spawn_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активировать доп. спавн после выброса.
        /// </summary>
        public static string dop_spawn_name {
            get {
                return ResourceManager.GetString("dop_spawn_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Динамические новости.
        /// </summary>
        public static string dynamic_news {
            get {
                return ResourceManager.GetString("dynamic_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает динамический вывод новостей и сообщений о гибели сталкеров.
        /// </summary>
        public static string dynamic_news_desc {
            get {
                return ResourceManager.GetString("dynamic_news_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        public static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность выпадения экзоскелетов при убийстве неписей в процентах. Регулируется в пределах от 1 до 15..
        /// </summary>
        public static string exo_prob_desc {
            get {
                return ResourceManager.GetString("exo_prob_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность выпадения экзоскелетов.
        /// </summary>
        public static string exo_prob_name {
            get {
                return ResourceManager.GetString("exo_prob_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должен быть в диапазоне [5,140].
        /// </summary>
        public static string fov_volume_desc {
            get {
                return ResourceManager.GetString("fov_volume_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на FOV (угол убзора).
        /// </summary>
        public static string fov_volume_name {
            get {
                return ResourceManager.GetString("fov_volume_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность эффекта Horizon-Based Ambient Occlusion. Регулируется в процентах от 0 до 100..
        /// </summary>
        public static string hbao_int_desc {
            get {
                return ResourceManager.GetString("hbao_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность HBAO.
        /// </summary>
        public static string hbao_int_name {
            get {
                return ResourceManager.GetString("hbao_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некая имитация вторичного освещения для SSDO. Уменьшает производительность, зато тени не черные, а более реалистичные..
        /// </summary>
        public static string indirect_bounce_desc {
            get {
                return ResourceManager.GetString("indirect_bounce_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вторичное освещение для SSDO.
        /// </summary>
        public static string indirect_bounce_name {
            get {
                return ResourceManager.GetString("indirect_bounce_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция  включает длинный горизонтальный блик на лампах.
        /// </summary>
        public static string long_flare_desc {
            get {
                return ResourceManager.GetString("long_flare_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длинный блик от ламп.
        /// </summary>
        public static string long_flare_name {
            get {
                return ResourceManager.GetString("long_flare_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает плавное наполнение здоровья персонажа при употреблении аптечек, делая игру реалистичнее..
        /// </summary>
        public static string medlen_lek_desc {
            get {
                return ResourceManager.GetString("medlen_lek_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Медленное лечение аптечками.
        /// </summary>
        public static string medlen_lek_name {
            get {
                return ResourceManager.GetString("medlen_lek_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Множитель респавна.
        /// </summary>
        public static string mnog_resp_name {
            get {
                return ResourceManager.GetString("mnog_resp_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция  включает отражение солнца и луны от воды - т.н. &quot;лунную дорожку&quot;.
        /// </summary>
        public static string moonroad_desc {
            get {
                return ResourceManager.GetString("moonroad_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лунная дорожка.
        /// </summary>
        public static string moonroad_name {
            get {
                return ResourceManager.GetString("moonroad_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это коэффициент диапазона времени выдачи сообщений - чем он меньше, тем чаще выдаются сообщения.
        /// </summary>
        public static string news_freq_desc {
            get {
                return ResourceManager.GetString("news_freq_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частота выдачи новостей.
        /// </summary>
        public static string news_freq_name {
            get {
                return ResourceManager.GetString("news_freq_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось соединиться с сервером. Проверьте соединение интернет.
        /// </summary>
        public static string no_internet {
            get {
                return ResourceManager.GetString("no_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует файл локализации OGSE.
        /// </summary>
        public static string NO_LOCALE {
            get {
                return ResourceManager.GetString("NO_LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлений нет.
        /// </summary>
        public static string no_update {
            get {
                return ResourceManager.GetString("no_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NPC.
        /// </summary>
        public static string NPC {
            get {
                return ResourceManager.GetString("NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выкл.
        /// </summary>
        public static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта настройка включает режим оффлайновой симуляции жизни. NPC будут сражаться в оффлайне друг с другом и монстрами, собирать вещи и оружие. События в оффлайне будут появляться в новостях..
        /// </summary>
        public static string offline_alife_desc {
            get {
                return ResourceManager.GetString("offline_alife_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оффлайн-алайф.
        /// </summary>
        public static string offline_alife_name {
            get {
                return ResourceManager.GetString("offline_alife_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вкл.
        /// </summary>
        public static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Патч загружен!.
        /// </summary>
        public static string patch_downloaded {
            get {
                return ResourceManager.GetString("patch_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Периодичность респауна нововведенных монстров в игровых часах. К этому значению также добавляется случайная поправка от минус одного до плюс одного часа..
        /// </summary>
        public static string period_resp_new_desc {
            get {
                return ResourceManager.GetString("period_resp_new_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период респавна новых NPC.
        /// </summary>
        public static string period_resp_new_name {
            get {
                return ResourceManager.GetString("period_resp_new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Периодичность респауна обычных монстров и людей в игровых часах. Если указать 0, то респаун будет происходить сразу, как только на локации освободится место для объектов..
        /// </summary>
        public static string period_resp_old_desc {
            get {
                return ResourceManager.GetString("period_resp_old_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Период респавна стандартных NPC.
        /// </summary>
        public static string period_resp_old_name {
            get {
                return ResourceManager.GetString("period_resp_old_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок.
        /// </summary>
        public static string player {
            get {
                return ResourceManager.GetString("player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает эффекты камеры в зависимости от самочувствия персонажа..
        /// </summary>
        public static string plohoe_samochustv_desc {
            get {
                return ResourceManager.GetString("plohoe_samochustv_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эффект плохого самочувствия.
        /// </summary>
        public static string plohoe_samochustv_name {
            get {
                return ResourceManager.GetString("plohoe_samochustv_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматическое включение ПНВ при прицеливании.
        /// </summary>
        public static string pnv_autostart_desc {
            get {
                return ResourceManager.GetString("pnv_autostart_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПНВ: автостарт при прицеливании.
        /// </summary>
        public static string pnv_autostart_name {
            get {
                return ResourceManager.GetString("pnv_autostart_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опция отключает эффект ночного видения во время прицеливания через прицел или использования бинокля. Прицелы и бинокль со встроенным ПНВ будут работать, как и раньше..
        /// </summary>
        public static string pnv_disabling_desc {
            get {
                return ResourceManager.GetString("pnv_disabling_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПНВ: отключение при прицеливании.
        /// </summary>
        public static string pnv_disabling_name {
            get {
                return ResourceManager.GetString("pnv_disabling_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает эффекты отравления при злоупотреблении лекарствами..
        /// </summary>
        public static string poboch_lek_desc {
            get {
                return ResourceManager.GetString("poboch_lek_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Побочные эффекты лекарств.
        /// </summary>
        public static string poboch_lek_name {
            get {
                return ResourceManager.GetString("poboch_lek_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string popadanie_po_ger_desc {
            get {
                return ResourceManager.GetString("popadanie_po_ger_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эффекты попадания по главгерою.
        /// </summary>
        public static string popadanie_po_ger_name {
            get {
                return ResourceManager.GetString("popadanie_po_ger_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает происходящие после обычных выбросов пси-выбросы,с вероятностью, зависящей от локации..
        /// </summary>
        public static string psy_surges_desc {
            get {
                return ResourceManager.GetString("psy_surges_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пси-выбросы.
        /// </summary>
        public static string psy_surges_name {
            get {
                return ResourceManager.GetString("psy_surges_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция управляет спавном пси-зон: обновлять после пси-выбросов, обычных выбросов или отключить пси-зоны..
        /// </summary>
        public static string psyzones_desc {
            get {
                return ResourceManager.GetString("psyzones_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отключены.
        /// </summary>
        public static string psyzones_disabled {
            get {
                return ResourceManager.GetString("psyzones_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пси-зоны.
        /// </summary>
        public static string psyzones_name {
            get {
                return ResourceManager.GetString("psyzones_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на привязаны к пси-выбросу.
        /// </summary>
        public static string psyzones_to_psyvybros {
            get {
                return ResourceManager.GetString("psyzones_to_psyvybros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на привязаны к выбросу.
        /// </summary>
        public static string psyzones_to_vybros {
            get {
                return ResourceManager.GetString("psyzones_to_vybros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость образования луж во время дождя. Регулируется в процентах от 0 до 100..
        /// </summary>
        public static string puddles_grow_desc {
            get {
                return ResourceManager.GetString("puddles_grow_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость роста луж.
        /// </summary>
        public static string puddles_grow_name {
            get {
                return ResourceManager.GetString("puddles_grow_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При включении этой опции содержимое всех тайников в игре, кроме именных, выбирается произвольно..
        /// </summary>
        public static string random_stashes_desc {
            get {
                return ResourceManager.GetString("random_stashes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайное содержимое тайников.
        /// </summary>
        public static string random_stashes_name {
            get {
                return ResourceManager.GetString("random_stashes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность эффекта глубины поля зрения при перезарядке. Регулируется в процентах от 0 до 100..
        /// </summary>
        public static string rdof_int_desc {
            get {
                return ResourceManager.GetString("rdof_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность DOF при перезарядке.
        /// </summary>
        public static string rdof_int_name {
            get {
                return ResourceManager.GetString("rdof_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объемный свет.
        /// </summary>
        public static string shafts {
            get {
                return ResourceManager.GetString("shafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При включении этой опции во всплывающей подсказке к тайнику будет перечислено его содержимое..
        /// </summary>
        public static string show_stashes_desc {
            get {
                return ResourceManager.GetString("show_stashes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение содержимого тайника.
        /// </summary>
        public static string show_stashes_name {
            get {
                return ResourceManager.GetString("show_stashes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает динамический сон NPC. Ночью они будут вялые, и при отсутствии опасности будут пытаться поспать..
        /// </summary>
        public static string son_desc {
            get {
                return ResourceManager.GetString("son_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить сон.
        /// </summary>
        public static string son_name {
            get {
                return ResourceManager.GetString("son_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция  включает имитацию пыли в саншафтах типа &quot;Crysis&quot;.
        /// </summary>
        public static string ss_dust_desc {
            get {
                return ResourceManager.GetString("ss_dust_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пыль в солнечных лучах.
        /// </summary>
        public static string ss_dust_name {
            get {
                return ResourceManager.GetString("ss_dust_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция  включает имитацию пыли в объемном свете ламп.
        /// </summary>
        public static string ss_volume_dust_desc {
            get {
                return ResourceManager.GetString("ss_volume_dust_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пыль в свете ламп.
        /// </summary>
        public static string ss_volume_dust_name {
            get {
                return ResourceManager.GetString("ss_volume_dust_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность эффекта Scrren Space Dynamic Occlusion. Регулируется в процентах от 0 до 100..
        /// </summary>
        public static string ssdo_int_desc {
            get {
                return ResourceManager.GetString("ssdo_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность SSDO.
        /// </summary>
        public static string ssdo_int_name {
            get {
                return ResourceManager.GetString("ssdo_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частота выпадения тайников при включенных рандомных тайниках. Цифра указывает процент вероятности..
        /// </summary>
        public static string stashes_desc {
            get {
                return ResourceManager.GetString("stashes_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность выпадения тайников, %.
        /// </summary>
        public static string stashes_name {
            get {
                return ResourceManager.GetString("stashes_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тайники.
        /// </summary>
        public static string stashes_settings {
            get {
                return ResourceManager.GetString("stashes_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность выпадения обычных костюмов при убийстве неписей в процентах. Регулируется в пределах от 1 до 25. Не влияет на вероятность выпадения экзоскелетов..
        /// </summary>
        public static string suit_prob_desc {
            get {
                return ResourceManager.GetString("suit_prob_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность выпадения брони.
        /// </summary>
        public static string suit_prob_name {
            get {
                return ResourceManager.GetString("suit_prob_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указывается в игровых часах. К этому значению также добавляется случайная поправка от минус четырех до плюс четырёх часов.
        /// </summary>
        public static string surge_timer_desc {
            get {
                return ResourceManager.GetString("surge_timer_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Периодичность выброса.
        /// </summary>
        public static string surge_timer_name {
            get {
                return ResourceManager.GetString("surge_timer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость для демонстрации смены дня и ночи. Чем меньше, тем дольше идут сутки.
        /// </summary>
        public static string time_factor_desc {
            get {
                return ResourceManager.GetString("time_factor_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость хода времени.
        /// </summary>
        public static string time_factor_name {
            get {
                return ResourceManager.GetString("time_factor_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время начала игры.
        /// </summary>
        public static string time_start_name {
            get {
                return ResourceManager.GetString("time_start_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно обновление.
        /// </summary>
        public static string update_available {
            get {
                return ResourceManager.GetString("update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочее.
        /// </summary>
        public static string various {
            get {
                return ResourceManager.GetString("various", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должен быть в диапазоне [40,100] кг.
        /// </summary>
        public static string ves_desc {
            get {
                return ResourceManager.GetString("ves_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предельный переносимый вес, кг.
        /// </summary>
        public static string ves_name {
            get {
                return ResourceManager.GetString("ves_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция  включает эффект виньетирования (затемнение по краям изображения, н-р, для широкоугольных объективов).
        /// </summary>
        public static string vignette_desc {
            get {
                return ResourceManager.GetString("vignette_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность эффекта виньетирования. Регулируется в процентах от 0 до 100. 100 - пиксели по краям экрана полностью черные..
        /// </summary>
        public static string vignette_int_desc {
            get {
                return ResourceManager.GetString("vignette_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность виньетирования.
        /// </summary>
        public static string vignette_int_name {
            get {
                return ResourceManager.GetString("vignette_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Виньетирование.
        /// </summary>
        public static string vignette_name {
            get {
                return ResourceManager.GetString("vignette_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция регулирует интенсивность объемного света. Регулируется в процентах от 0 до 100..
        /// </summary>
        public static string vol_light_max_int_desc {
            get {
                return ResourceManager.GetString("vol_light_max_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность света ламп.
        /// </summary>
        public static string vol_light_max_int_name {
            get {
                return ResourceManager.GetString("vol_light_max_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция  регулирует интенсивность объемных лучей (тип &apos;Clear Sky&apos;) от солнца. Регулируется в процентах от 0 до 100..
        /// </summary>
        public static string vol_max_int_desc {
            get {
                return ResourceManager.GetString("vol_max_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность солнечных лучей.
        /// </summary>
        public static string vol_max_int_name {
            get {
                return ResourceManager.GetString("vol_max_int_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дождитесь окончания скачивания.
        /// </summary>
        public static string wait_for_download {
            get {
                return ResourceManager.GetString("wait_for_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ясная.
        /// </summary>
        public static string weather_bright {
            get {
                return ResourceManager.GetString("weather_bright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стандартная.
        /// </summary>
        public static string weather_default {
            get {
                return ResourceManager.GetString("weather_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дождливая.
        /// </summary>
        public static string weather_rainy {
            get {
                return ResourceManager.GetString("weather_rainy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта настройка позволяет регулировать погоду в игре.
        /// </summary>
        public static string weather_type_desc {
            get {
                return ResourceManager.GetString("weather_type_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Погода.
        /// </summary>
        public static string weather_type_name {
            get {
                return ResourceManager.GetString("weather_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окружающий мир.
        /// </summary>
        public static string world_settings {
            get {
                return ResourceManager.GetString("world_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта опция включает забрызгивание стекла маски кровью при убийстве НПС в упор..
        /// </summary>
        public static string zalyap_hud_desc {
            get {
                return ResourceManager.GetString("zalyap_hud_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Брызги крови на маске.
        /// </summary>
        public static string zalyap_hud_name {
            get {
                return ResourceManager.GetString("zalyap_hud_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность эффекта глубины поля зрения при прицеливании. Регулируется в процентах от 0 до 100..
        /// </summary>
        public static string zdof_int_desc {
            get {
                return ResourceManager.GetString("zdof_int_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интенсивность DOF при прицеливании.
        /// </summary>
        public static string zdof_int_name {
            get {
                return ResourceManager.GetString("zdof_int_name", resourceCulture);
            }
        }
    }
}
